name: Docker Image CI

on:
    release:
        types: [published]

jobs:
    build_image:
        name: Build and publish Docker image
        runs-on: ubuntu-latest

        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set VERSION variable from tag
              run: |
                  TAG=${{ github.event.release.tag_name }}
                  echo "VERSION=${TAG#v}" >> $GITHUB_ENV

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: cyrilschreiber/pivpn-web:latest,cyrilschreiber/pivpn-web:${{ env.VERSION }}
                  platforms: linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64
